import { Product, Vendor, Location, Category } from '@/types/product';

export const locations: Location[] = [
  { id: '1', name: 'Oslo', translationKey: 'oslo' },
  { id: '2', name: 'Bergen', translationKey: 'bergen' },
  { id: '3', name: 'Trondheim', translationKey: 'trondheim' },
  { id: '4', name: 'Stavanger', translationKey: 'stavanger' },
];

export const categories: Category[] = [
  { id: '1', name: 'Vegetables', translationKey: 'vegetables' },
  { id: '2', name: 'Fruits', translationKey: 'fruits' },
  { id: '3', name: 'Herbs', translationKey: 'herbs' },
  { id: '4', name: 'Dairy', translationKey: 'dairy' },
];

export const vendors: Vendor[] = [
  {
    id: '1',
    name: 'Fresh Farm Oslo',
    phone: '+47 123 45 678',
    whatsapp: '+47123456789',
    location: locations[0],
    description: 'Organic vegetables and fruits from our family farm',
    translationKey: 'freshFarmOslo',
  },
  {
    id: '2',
    name: 'Bergen Greens',
    phone: '+47 234 56 789',
    whatsapp: '+47234567890',
    location: locations[1],
    description: 'Fresh local produce delivered daily',
    translationKey: 'bergenGreens',
  },
  {
    id: '3',
    name: 'Nordic Harvest',
    phone: '+47 345 67 890',
    whatsapp: '+47345678901',
    location: locations[2],
    description: 'Seasonal Norwegian vegetables and herbs',
    translationKey: 'nordicHarvest',
  },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    title: 'Organic Tomatoes',
    description: 'Fresh, locally grown organic tomatoes. Perfect for salads and cooking.',
    price: 45,
    unit: 'kg',
    category: categories[0],
    vendor: vendors[0],
    location: locations[0],
    inStock: true,
    updatedAt: new Date('2024-02-17T08:00:00'),
    images: ['https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=800&q=80'],
    featured: true,
    translationKey: 'organicTomatoes',
  },
  {
    id: '2',
    title: 'Fresh Strawberries',
    description: 'Sweet Norwegian strawberries, freshly picked this morning.',
    price: 89,
    unit: 'kg',
    category: categories[1],
    vendor: vendors[1],
    location: locations[1],
    inStock: true,
    updatedAt: new Date('2024-02-17T07:30:00'),
    images: ['https://images.unsplash.com/photo-1543528176-61b239494933?w=800&q=80'],
    featured: true,
    translationKey: 'freshStrawberries',
  },
  {
    id: '3',
    title: 'Organic Carrots',
    description: 'Crunchy organic carrots, great for snacking or cooking.',
    price: 35,
    unit: 'kg',
    category: categories[0],
    vendor: vendors[0],
    location: locations[0],
    inStock: true,
    updatedAt: new Date('2024-02-17T06:00:00'),
    images: ['https://images.unsplash.com/photo-1447175008436-054170c2e979?w=800&q=80'],
    featured: false,
    translationKey: 'organicCarrots',
  },
  {
    id: '4',
    title: 'Fresh Basil',
    description: 'Aromatic fresh basil, perfect for pasta and salads.',
    price: 25,
    unit: 'bunch',
    category: categories[2],
    vendor: vendors[2],
    location: locations[2],
    inStock: true,
    updatedAt: new Date('2024-02-17T09:00:00'),
    images: ['https://images.unsplash.com/photo-1618164436241-4473940d1f5c?w=800&q=80'],
    featured: true,
    translationKey: 'freshBasil',
  },
  {
    id: '5',
    title: 'Norwegian Apples',
    description: 'Crisp and sweet apples from local orchards.',
    price: 55,
    unit: 'kg',
    category: categories[1],
    vendor: vendors[1],
    location: locations[1],
    inStock: true,
    updatedAt: new Date('2024-02-17T07:00:00'),
    images: ['https://images.unsplash.com/photo-1619546813926-a78fa6372cd2?w=800&q=80'],
    featured: true,
    translationKey: 'norwegianApples',
  },
  {
    id: '6',
    title: 'Fresh Lettuce',
    description: 'Crispy green lettuce, harvested this morning.',
    price: 30,
    unit: 'item',
    category: categories[0],
    vendor: vendors[0],
    location: locations[0],
    inStock: true,
    updatedAt: new Date('2024-02-17T08:30:00'),
    images: ['https://images.unsplash.com/photo-1556801712-76c8eb07bbc9?w=800&q=80'],
    featured: true,
    translationKey: 'freshLettuce',
  },
  {
    id: '7',
    title: 'Cherry Tomatoes',
    description: 'Sweet and juicy cherry tomatoes, great for snacking.',
    price: 65,
    unit: 'kg',
    category: categories[0],
    vendor: vendors[2],
    location: locations[2],
    inStock: false,
    updatedAt: new Date('2024-02-16T15:00:00'),
    images: ['https://cdn.mos.cms.futurecdn.net/WaZM7X6HxT5pEZQThL9TLE.jpg'],
    featured: false,
    translationKey: 'cherryTomatoes',
  },
  {
    id: '8',
    title: 'Fresh Parsley',
    description: 'Fresh parsley for garnishing and cooking.',
    price: 20,
    unit: 'bunch',
    category: categories[2],
    vendor: vendors[2],
    location: locations[2],
    inStock: true,
    updatedAt: new Date('2024-02-17T09:30:00'),
    images: ['http://www.redbarn.com/cdn/shop/articles/f43bd60b081c738fb1c45ce07f750976.jpg'],
    featured: false,
    translationKey: 'freshParsley',
  },
  {
    id: '9',
    title: 'Organic Potatoes',
    description: 'Versatile organic potatoes, perfect for any meal.',
    price: 28,
    unit: 'kg',
    category: categories[0],
    vendor: vendors[0],
    location: locations[0],
    inStock: true,
    updatedAt: new Date('2024-02-17T07:00:00'),
    images: ['https://images.unsplash.com/photo-1558818498-28c1e002b655?w=800&q=80'],
    featured: false,
    translationKey: 'organicPotatoes',
  },
  {
    id: '10',
    title: 'Blueberries',
    description: 'Fresh Norwegian blueberries, rich in antioxidants.',
    price: 120,
    unit: 'kg',
    category: categories[1],
    vendor: vendors[1],
    location: locations[1],
    inStock: true,
    updatedAt: new Date('2024-02-17T08:00:00'),
    images: ['https://nwwildfoods.com/cdn/shop/files/organic_blueberries.jpg'],
    featured: false,
    translationKey: 'blueberries',
  },
];
