import { Product, Vendor, Location, Category } from '@/types/product';

export const locations: Location[] = [
  { id: '1', name: 'Oslo' },
  { id: '2', name: 'Bergen' },
  { id: '3', name: 'Trondheim' },
  { id: '4', name: 'Stavanger' },
];

export const categories: Category[] = [
  { id: '1', name: 'Vegetables' },
  { id: '2', name: 'Fruits' },
  { id: '3', name: 'Herbs' },
  { id: '4', name: 'Dairy' },
];

export const vendors: Vendor[] = [
  {
    id: '1',
    name: 'Fresh Farm Oslo',
    phone: '+47 123 45 678',
    whatsapp: '+47123456789',
    location: locations[0],
    description: 'Organic vegetables and fruits from our family farm',
  },
  {
    id: '2',
    name: 'Bergen Greens',
    phone: '+47 234 56 789',
    whatsapp: '+47234567890',
    location: locations[1],
    description: 'Fresh local produce delivered daily',
  },
  {
    id: '3',
    name: 'Nordic Harvest',
    phone: '+47 345 67 890',
    whatsapp: '+47345678901',
    location: locations[2],
    description: 'Seasonal Norwegian vegetables and herbs',
  },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    title: 'Organic Tomatoes',
    description: 'Fresh, locally grown organic tomatoes. Perfect for salads and cooking.',
    price: 45,
    unit: 'kg',
    category: categories[0],
    vendor: vendors[0],
    location: locations[0],
    inStock: true,
    updatedAt: new Date('2024-02-17T08:00:00'),
    images: ['https://images.unsplash.com/photo-1546470427-227bf6e4cf9e?w=800'],
    featured: true,
  },
  {
    id: '2',
    title: 'Fresh Strawberries',
    description: 'Sweet Norwegian strawberries, freshly picked this morning.',
    price: 89,
    unit: 'kg',
    category: categories[1],
    vendor: vendors[1],
    location: locations[1],
    inStock: true,
    updatedAt: new Date('2024-02-17T07:30:00'),
    images: ['https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=800'],
    featured: true,
  },
  {
    id: '3',
    title: 'Organic Carrots',
    description: 'Crunchy organic carrots, great for snacking or cooking.',
    price: 35,
    unit: 'kg',
    category: categories[0],
    vendor: vendors[0],
    location: locations[0],
    inStock: true,
    updatedAt: new Date('2024-02-17T06:00:00'),
    images: ['https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=800'],
    featured: false,
  },
  {
    id: '4',
    title: 'Fresh Basil',
    description: 'Aromatic fresh basil, perfect for pasta and salads.',
    price: 25,
    unit: 'bunch',
    category: categories[2],
    vendor: vendors[2],
    location: locations[2],
    inStock: true,
    updatedAt: new Date('2024-02-17T09:00:00'),
    images: ['https://images.unsplash.com/photo-1618375569909-3c8616cf7733?w=800'],
    featured: true,
  },
  {
    id: '5',
    title: 'Norwegian Apples',
    description: 'Crisp and sweet apples from local orchards.',
    price: 55,
    unit: 'kg',
    category: categories[1],
    vendor: vendors[1],
    location: locations[1],
    inStock: true,
    updatedAt: new Date('2024-02-17T07:00:00'),
    images: ['https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=800'],
    featured: true,
  },
  {
    id: '6',
    title: 'Fresh Lettuce',
    description: 'Crispy green lettuce, harvested this morning.',
    price: 30,
    unit: 'item',
    category: categories[0],
    vendor: vendors[0],
    location: locations[0],
    inStock: true,
    updatedAt: new Date('2024-02-17T08:30:00'),
    images: ['https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=800'],
    featured: true,
  },
  {
    id: '7',
    title: 'Cherry Tomatoes',
    description: 'Sweet and juicy cherry tomatoes, great for snacking.',
    price: 65,
    unit: 'kg',
    category: categories[0],
    vendor: vendors[2],
    location: locations[2],
    inStock: false,
    updatedAt: new Date('2024-02-16T15:00:00'),
    images: ['https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=800'],
    featured: false,
  },
  {
    id: '8',
    title: 'Fresh Parsley',
    description: 'Fresh parsley for garnishing and cooking.',
    price: 20,
    unit: 'bunch',
    category: categories[2],
    vendor: vendors[2],
    location: locations[2],
    inStock: true,
    updatedAt: new Date('2024-02-17T09:30:00'),
    images: ['https://images.unsplash.com/photo-1572281299236-f156f980f217?w=800'],
    featured: false,
  },
  {
    id: '9',
    title: 'Organic Potatoes',
    description: 'Versatile organic potatoes, perfect for any meal.',
    price: 28,
    unit: 'kg',
    category: categories[0],
    vendor: vendors[0],
    location: locations[0],
    inStock: true,
    updatedAt: new Date('2024-02-17T07:00:00'),
    images: ['https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=800'],
    featured: false,
  },
  {
    id: '10',
    title: 'Blueberries',
    description: 'Fresh Norwegian blueberries, rich in antioxidants.',
    price: 120,
    unit: 'kg',
    category: categories[1],
    vendor: vendors[1],
    location: locations[1],
    inStock: true,
    updatedAt: new Date('2024-02-17T08:00:00'),
    images: ['https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=800'],
    featured: false,
  },
];
